Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('app.urls')),
]

if settings.DEBUG :
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from pathlib import Path
from django.urls import path
from .views import (HomeView,ItemDetailView, OrderSummaryView,CheckoutView,
                    add_to_cart,remove_from_cart,OrderSummaryView,
                    remove_item_from_cart,add_item_to_cart,PaymentView,AddCoupon,
                    RequestRefundView)


urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('checkout/',CheckoutView.as_view(),name='checkout'),
    path('product/<slug>/',ItemDetailView.as_view(),name='product'),
    path('add_to_cart/<slug>/',add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<slug>/',remove_from_cart,name='remove_from_cart'),
    path('order_summary/',OrderSummaryView.as_view(),name='order_summary'),
    path('remove_item_from_cart/<slug>/',remove_item_from_cart,name='remove_item_from_cart'),
    path('add_item_to_cart/<slug>/',add_item_to_cart,name='add_item_to_cart'),
    path('payment/<payment_option>/',PaymentView.as_view(),name='payment'),
    path('add_coupon/',AddCoupon.as_view(),name='add_coupon'),
    path('request_refund/',RequestRefundView.as_view(),name='request_refund')

]

app/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.conf import settings
from django.contrib.auth.models import User



CATEGORY_CHOICES = (
    ('S','Shirt'),
    ('SW','Sport Wear'),
    ('O','Native_wear')
)

LABEL_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('D','danger')
)
ADDRESS_CHOICES = (
    ('B','billing_address'),
    ('S','shipping_address'),
)


class UserProfile(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,blank=True,null=True)
    stripe_customer_id = models.CharField(max_length=50,blank=True,null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField('this item should come with a description')
    image = models.ImageField(blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("add_to_cart",kwargs={'slug':self.slug})

    def get_remove_from_cart_url(self):
        return reverse("remove_from_cart",kwargs={'slug':self.slug})



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,blank=True,null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} {self.item.title}s"

    def get_total_item_price(self):

        return self.item.price * self.quantity

    def get_total_discount_item_price(self):

        return self.item.discount_price * self.quantity

    def get_total_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):

        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()




class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    
    ref_code = models.CharField(max_length=20)

    items = models.ManyToManyField(OrderItem)

    start_date = models.DateField(auto_now_add=True)

    ordered_date = models.DateField()

    ordered = models.BooleanField(default=False)

    billing_address = models.ForeignKey('Address',related_name='billing_address',
                                        on_delete=models.SET_NULL,blank=True,null=True)
    shipping_address = models.ForeignKey('Address',related_name='shipping_address',
                                        on_delete=models.SET_NULL,blank=True,null=True)

    payment = models.ForeignKey('Payment',
                                        on_delete=models.SET_NULL,blank=True,null=True)

    coupon = models.ForeignKey('Coupon',
                                        on_delete=models.SET_NULL,blank=True,null=True)

    being_delivered = models.BooleanField(default=False)
    recieved = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)                                    

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0

        for order_item in self.items.all():
            total += order_item.get_final_price()
        
        if self.coupon and total != 0:
            total -= self.coupon.amount



        return total

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    
    street_address = models.CharField(max_length = 100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1,choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name_plural = "Addresses"


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user =  user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL,blank=True,null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=50)
    amount = models.FloatField()
    

    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey('Order',on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


    


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}
{% load carts_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% block title %} <title>DRINK SHOP</title> {% endblock title %}
  {% block extra_head %}
  {% endblock extra_head %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href='{% static "css/mdb.min.css" %}' rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href='{% static "css/style.min.css" %}' rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>


<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href='{% url 'home' %}'>
        <strong class="blue-text">MIDE-ECOMMERCE</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %}<li class="nav-item active">
            <a class="nav-link waves-effect" href={% url 'home' %}>HOME
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href={% url 'checkout' %} target="_blank">CHECKOUT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href=""
              target="_blank">PRODUCTS</a>
          </li>{% endcomment %}
          
        </ul>

        <!-- Right -->
        
        <ul class="navbar-nav nav-flex-icons">
          {% if  request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href={% url 'order_summary' %}>
              <span class="badge red z-depth-1 mr-1"> {{ request.user | cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
            <li class="nav-item">
            <a class="nav-link waves-effect" href={% url 'account_logout' %}>
              <span class="clearfix d-none d-sm-inline-block"> LOGOUT </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="">
              <span class="clearfix d-none d-sm-inline-block"> {{ user.username }} </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href={% url 'account_login' %}>
              <span class="clearfix d-none d-sm-inline-block">LOGIN</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href={% url 'account_signup' %}>
              <span class="clearfix d-none d-sm-inline-block">Signup</span>
            </a>
          </li>
          {% endif %}

        </ul>


      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
    {% block content %}


    {% endblock content %}
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

  <!--Call to action-->
  <div class="pt-4">
    <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
      role="button">Download MDB
      <i class="fas fa-download ml-2"></i>
    </a>
    <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
      free tutorial
      <i class="fas fa-graduation-cap ml-2"></i>
    </a>
  </div>
  <!--/.Call to action-->

  <hr class="my-4">

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com/mdbootstrap" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/MDBootstrap" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src='{% static "js/jquery-3.4.1.min.js" %}'></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src='{% static "js/popper.min.js" %}'></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src='{% static "js/bootstrap.min.js" %}'></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src='{% static "js/mdb.min.js" %}'></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
  {% block extra_scripts %}
  {% endblock extra_scripts %}
</body>
</html>

templates/home-page.html
{% extends 'base.html' %}

{% block title %} <title>DRINK SHOP</title> {% endblock title %}

{% block content %}





  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in items %}

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-6">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{item.image.url}}" class="card-img-top "
                  alt="Image">
                <a
                  href = "{{ item.get_absolute_url}}" >
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url}}" class="dark-grey-text">{{item.title}}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">New</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  {% if item.discount_price %}
                  <strong>${{ item.discount_price}}</strong>
                  {% else %}
                  <strong>${{ item.price}}</strong>
                  {% endif %}

                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->

          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
    {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number}}">{{ page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
      
         {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

  
{% endblock content %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}

<h2> here is the list of items </h2>

{% for item in items %}

     {{ item }}

{% endfor %}

{% endblock content %}

templates/product-page.html
{% extends 'base.html' %}

{% block title %} <title>PRODUCT PAGE</title> {% endblock title %}

{% block content %}

<body>

  

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{item.image.url}}" class="card-img-top"
                  alt="Image">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ item.get_category_display}}</span>
              </a>
            </div>

            <p class="lead">
              {% if item.discount_price %}
              <span class="mr-1">
                <del>${{ item.price}}</del>
              </span>
              <span>${{ item.discount_price}}</span>
              {% else %}
              <span>${{ item.price}}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ item.description }}</p>

            {% comment %}<form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
            </form>{% endcomment %}

            <a href="{{ item.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ item.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p">Delete
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

</body>
{% endblock content %}

</html>

templates/request_refund.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} <title>REQUEST FUND PAGE</title> {% endblock title %}

{% block content %}
<main>
    <div class='container'>
    <h2>REQUEST FUND</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ form|crispy}}
        <button class='btn btn-primary' type='submit'>SUBMIT</button>
    </form>
    </div>
</main>






{% endblock content %}